probes:
  - name: latency
    type: std_fping
    output:
      - vodka
    groups:
      - name: public_dns
        hosts:
          - host: 8.8.8.8
            name: Google
            color: red
          - host: 4.2.2.1
            name: Level(3)
            color: blue
          - host: 208.67.222.222
            name: OpenDNS
            color: orange
      - name: gcp
        hosts:
          - host: 35.211.175.212
            name: github
            color: yellow
          - host: 34.75.165.172
            name: te02gcpuseast1
            color: green
  - name: mtr
    type: fping_mtr
    group: mtr.gcp_github
    host: 35.211.175.212
    output:
      - vodka

plugins:
  - name: std_fping
    type: fping
    count: 10
    interval: 3s
    period: 100
    output:
      - vodka

  - name: vodka
    type: vodka

    data:
      - type: fping
        handlers:
          - type: index
            index: host
          - type: store
            container: list
            limit: 500
      - type: fping_mtr
        handlers:
          - type: index
            index: host
          - type: store
            container: list
            limit: 100
    apps:
      graphsrv:
        enabled: true
        graphs:
          multitarget:
            id_field: host
            type: multitarget
            plot_y: avg
            format_y: ms

          smokestack:
            id_field: host
            type: smokestack
            plot_y: avg

    plugins:
      - name: http
        type: flask
        bind: 0.0.0.0:8080
        debug: true
        static_url_path: /static
        server: self
        async: thread
        routes:
          /targets : graphsrv->targets
          /graph_data :
            methods:
              - POST
              - GET
            target: graphsrv->graph_data
          /graph : graphsrv->graph_view
          /overview_read_file : graphsrv->overview_read_file
          /: graphsrv->overview_view

logging:
  version: 1
  formatters:
    simple:
      format: '%(asctime)s - %(name)s - %(levelname)s: %(message)s'
  handlers:
    console:
      class: logging.StreamHandler
      level: DEBUG
      formatter: simple
      stream: ext://sys.stdout

    #file:
    #  class: logging.FileHandler
    #  level: DEBUG
    #  formatter: simple
    #  filename: /home/dev/sandbox/vaping/vaping.log

  loggers:
    vaping:
      level: DEBUG
      handlers:
        - console
        #- file
    vodka:
      level: DEBUG
      handlers:
        - console
        #- file
